### ISSUE TITLE
Include instructions for installing pip in README

### ISSUE THREAD

**Issue by nsivapalan** [sdulal/cs-exams-downloader#2]
`sudo easy_install pip`

source: http://stackoverflow.com/questions/17271319/installing-pip-on-mac-os-x

**Comment by sdulal** [comment]
Pip is a useful tool for getting python packages. However, this repo isn't really concerned with pip (and it doesn't require using pip, either). Not to mention, `sudo easy_install pip` is an OS-specific method of getting pip—think of all the Windows, Linux **and** Mac users! :-)

That said, I've added a link to pip's documentation in 1b429b4ee242a05c4f6d366929fdd507970cb62b. That site gives lots of info on pip (including why pip might be a good tool to use, as well as installation instructions)!

**Comment by nsivapalan** [comment]
Sounds good!
